export ZSH="$HOME/.oh-my-zsh"
DEFAULT_USER=$USER
ZSH_THEME="arrow"

plugins=(
  git
  npm
  zsh-autosuggestions
  zsh-completions
  zsh-syntax-highlighting
)

bindkey '^ ' autosuggest-accept

source $ZSH/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR=~/.nvm
 [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

source ~/.aliases
