export LANG="en_US.UTF-8"
export TERM="xterm-kitty"

DEFAULT_USER=$USER

source /usr/local/share/antigen/antigen.zsh
antigen init ~/.antigenrc

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

bindkey '^ ' autosuggest-accept
source ~/.aliases

autoload -U promptinit; promptinit
prompt pure
prompt_newline='%666v'
PROMPT=" $PROMPT"
PURE_PROMPT_SYMBOL='→'
