tap "beeftornado/rmtree"
tap "cormacrelf/tap"
tap "homebrew/cask-fonts"
tap "iamjesper/homebrew-formulae"
tap "koekeishiya/formulae"
tap "nextdns/tap"
tap "ojford/formulae"

brew "antibody"
brew "autojump"
brew "bat"
brew "brew-rmtree"
brew "coreutils"
brew "dark-mode"
brew "dark-notify"
brew "exa"
brew "fnm"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "hub"
brew "jq"
brew "lazygit"
brew "lf"
brew "loginitems"
brew "moreutils"
brew "neovim", args: ['head']
brew "python"
brew "ripgrep"
brew "ruby"
brew "skhd"
brew "terminal-notifier"
brew "tldr"
brew "trash"
brew "tree"
brew "watchexec"
brew "yabai"
brew "zsh"

cask_args force: true
cask "1password"
cask "appcleaner"
cask "choosy"
cask "firefox"
cask "font-iosevka"
cask "google-chrome"
cask "iina"
cask "istat-menus"
cask "kitty"
cask "launchcontrol"
cask "macs-fan-control"
cask "mullvadvpn"
cask "pocket-casts"
cask "selfcontrol"
cask "spaceid"
cask "spotify"
cask "spotmenu"
cask "sublime-merge"

mas "Dark Reader for Safari", id: 1438243180
mas "NextDNS", id: 1464122853
mas "Vimari", id: 1480933944
