tap "beeftornado/rmtree"
tap "clementtsang/bottom"
tap "cormacrelf/tap"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "jryom/homebrew-formulae"
tap "koekeishiya/formulae"
tap "nextdns/tap"
tap "ojford/formulae"

brew "antibody"
brew "bat"
brew "bottom"
brew "brew-rmtree"
brew "coreutils"
brew "dark-mode"
brew "dark-notify"
brew "findutils"
brew "fnm"
brew "fzf"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "hub"
brew "jq"
brew "lazygit"
brew "lf"
brew "loginitems"
brew "moreutils"
brew "neovim"
brew "python"
brew "ripgrep"
brew "skhd"
brew "so"
brew "terminal-notifier"
brew "tldr"
brew "trash"
brew "tree"
brew "watchexec"
brew "yabai"
brew "z"
brew "zsh"

cask_args force: true

cask "1password"
cask "alfred"
cask "appcleaner"
cask "browserstacklocal"
cask "choosy"
cask "docker"
cask "firefox"
cask "font-iosevka"
cask "google-chrome"
cask "istat-menus"
cask "itsycal"
cask "kitty"
cask "launchcontrol"
cask "macs-fan-control"
cask "mullvadvpn"
cask "omnidisksweeper"
cask "selfcontrol"
cask "slack"
cask "sonos"
cask "spaceid"
cask "spotify"
cask "sublime-merge"

mas "Dark Reader for Safari", id: 1438243180
mas "NextDNS", id: 1464122853
mas "Tampermonkey", id: 1482490089
mas "Vimari", id: 1480933944
