#!/usr/bin/env sh

yabai -m config window_opacity               on
yabai -m config normal_window_opacity        0.90
yabai -m config auto_balance                 off
yabai -m config mouse_action1                move
yabai -m config mouse_modifier               fn
yabai -m config active_window_border_color   0xffdddddd
yabai -m config normal_window_border_color   0xff777777
yabai -m config split_ratio                  0.50
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config window_placement             second_child

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5
