#!/usr/bin/env bash

export PATH=/opt/homebrew/bin:$PATH

if command -v zoxide >/dev/null 2>&1; then eval "$(zoxide init bash --cmd j)"; fi

alias ll="ls -lah --color=never"
alias ..="cd .."

set -o vi
