#!/usr/bin/env zsh

theme=$([[ "$argv" = "light" ]] && echo "$KITTY_THEME_LIGHT" || echo "$KITTY_THEME_DARK")
kitty @ --to unix:/tmp/mykitty set-colors -a -c ~/.config/kitty/themes/$theme.conf
ln -sf ~/.config/kitty/themes/$theme.conf ~/.config/kitty/theme.conf
