#!/usr/bin/env bash

source "$HOME/.config/zsh/env"
export PATH="/usr/local/bin/:$PATH"
export SUDO_ASKPASS="$HOME/.config/scripts/askpass"

sudo -v
while true; do
  sudo -n true
  sleep 60
  kill -0 "$$" || exit
done 2>/dev/null &

eval "$(fnm env)"

set -x

INSTALLED=($(npm ls --json -g | jq -r '.dependencies | keys[]' | tr '\n' ' '))
UPGRADE_COMMAND="$(ncu --global | grep "." | grep "npm -g install" | tail -1)"

if fnm install --lts 2>&1 | grep "already"; then
  bash -c "$UPGRADE_COMMAND" || true
else
  fnm use lts-latest
  fnm default lts-latest
  npm --global --no-audit install "${INSTALLED[@]}"
fi

brew update
brew upgrade --greedy --force
export HOMEBREW_CLEANUP_MAX_AGE_DAYS=60
brew cleanup

tldr --update

antibody update
