#!/usr/bin/env sh

yabai -m config auto_balance                 on
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

yabai -m signal --add event=space_changed action="bash ~/.config/yabai/yabai-destroy_empty_spaces.sh"
