#!/usr/bin/env bash

updateWindowManagerSpacing() {
  output=$(system_profiler SPDisplaysDataType | grep "Looks like" | awk '{print int($6/60)}' | awk '{$1=$1};1')
  if [ -z "$output" ]; then
    output=$(system_profiler SPDisplaysDataType | grep Resolution | awk '{print int($4/120)}' | awk '{$1=$1};1')
  fi
  echo "$output"
}

export WM_SPACING="$(updateWindowManagerSpacing)"

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m rule --add manage=off app='1Password'
yabai -m rule --add manage=off app='Activity Monitor'
yabai -m rule --add manage=off app='Archive Utility'
yabai -m rule --add manage=off app='Bartender.'
yabai -m rule --add manage=off app='FaceTime'
yabai -m rule --add manage=off app='IINA'
yabai -m rule --add manage=off app='Installer'
yabai -m rule --add manage=off app='Messages'
yabai -m rule --add manage=off app='SoundID'
yabai -m rule --add manage=off app='System Information'
yabai -m rule --add manage=off app='System Settings'
yabai -m rule --add manage=off app='iStat'

yabai -m config layout bsp

yabai -m config top_padding "$WM_SPACING"
yabai -m config bottom_padding "$WM_SPACING"
yabai -m config left_padding "$WM_SPACING"
yabai -m config right_padding "$WM_SPACING"
yabai -m config window_gap "$WM_SPACING"

yabai -m config window_origin_display focused

yabai -m config normal_window_opacity 0.9
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.1
