#!/usr/bin/env bash

updateWindowManagerSpacing() {
  output=$(system_profiler SPDisplaysDataType | grep "Looks like" | awk '{print int($6/60)}' | awk '{$1=$1};1')
  if [ -z "$output" ]; then
    output=$(system_profiler SPDisplaysDataType | grep Resolution | awk '{print int($4/120)}' | awk '{$1=$1};1')
  fi
  echo "$output"
}

export WM_SPACING="$(updateWindowManagerSpacing)"

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m rule --add manage=off app='1Password'
yabai -m rule --add manage=off app='Activity Monitor'
yabai -m rule --add manage=off app='Archive Utility'
yabai -m rule --add manage=off app='Bartender.'
yabai -m rule --add manage=off app='FaceTime'
yabai -m rule --add manage=off app='IINA'
yabai -m rule --add manage=off app='Installer'
yabai -m rule --add manage=off app='Messages'
yabai -m rule --add manage=off app='SoundID'
yabai -m rule --add manage=off app='System Information'
yabai -m rule --add manage=off app='System Settings'
yabai -m rule --add manage=off app='Stats'

yabai -m config layout bsp

yabai -m config top_padding "$WM_SPACING"
yabai -m config bottom_padding "$WM_SPACING"
yabai -m config left_padding "$WM_SPACING"
yabai -m config right_padding "$WM_SPACING"
yabai -m config window_gap "$WM_SPACING"

yabai -m config window_origin_display focused

yabai -m config normal_window_opacity 0.9
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.1

yabai -m config window_opacity_duration 0.1

events=(
  "display_added"
  "display_removed"
  "display_resized"
  "mission_control_exit"
  "space_changed"
  "space_created"
  "space_destroyed"
)

window_events=(
  "application_hidden"
  "application_visible"
  "window_created"
  "window_deminimized"
  "window_destroyed"
  "window_focused"
  "window_minimized"
  "window_moved"
  "window_resized"
)

for event in "${events[@]}"; do
  yabai -m signal --add event="$event" action='echo "refresh" | nc -U /tmp/yabai-indicator.socket'
done

for event in "${window_events[@]}"; do
  yabai -m signal --add event="$event" action='echo "refresh windows" | nc -U /tmp/yabai-indicator.socket'
done
