#!/usr/bin/env fish

set -U WM_SPACING (updateWindowManagerSpacing)

launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist
sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_removed action="pkill yabai"

yabai -m rule --add manage=off app="^Ableton"
yabai -m rule --add manage=off app="^Archive Utility"
yabai -m rule --add manage=off app="^Installer*"
yabai -m rule --add manage=off app="System Settings"
yabai -m rule --add manage=off app="System Information"
yabai -m rule --add manage=off app="iStat*"

yabai -m config layout bsp

yabai -m config top_padding $WM_SPACING
yabai -m config bottom_padding $WM_SPACING
yabai -m config left_padding $WM_SPACING
yabai -m config right_padding $WM_SPACING
yabai -m config window_gap $WM_SPACING

yabai -m config window_origin_display focused

yabai -m config normal_window_opacity $WM_OPACITY
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.05
yabai -m config window_animation_duration 0.05
yabai -m config focus_follows_mouse autoraise
