#!/bin/sh

set -eu

target="$HOME/.config/yazi/plugins/smart-enter.yazi"
temp=$(mktemp -d)
trap 'rm -rf "$temp"' EXIT

git clone --depth=1 --filter=blob:none --sparse https://github.com/yazi-rs/plugins.git "$temp"
git -C "$temp" sparse-checkout set smart-enter.yazi

rm -rf "$target"
mkdir -p "$(dirname "$target")"
mv "$temp/smart-enter.yazi" "$target"
