#!/usr/bin/env fish

set -gx SUDO_ASKPASS "$HOME/.config/scripts/askpass"

sudo -v

set UPGRADE_COMMAND (ncu --global | grep "." | grep "npm --location=global install" | tail -1)

if test (nvm install --lts 2>&1 | grep --invert-match "installing")
    if test ! -z "$UPGRADE_COMMAND"
        fish -c "$UPGRADE_COMMAND"
    end
end

brew update
brew upgrade --greedy --force

tldr --update
