#!/usr/bin/env dash

echo "$1" >/tmp/dark-mode
theme="zenbones-$(cat /tmp/dark-mode || 'light')"
kitty @ --to unix:/tmp/mykitty set-colors -a -c "$HOME/.config/kitty/themes/$theme.conf"
ln -sf "$HOME/.config/kitty/themes/$theme.conf" ~/.config/kitty/theme.conf

if [ "$1" = "light" ]; then
  fish -i -c "set -Ux AICHAT_LIGHT_THEME 1"
else
  fish -i -c "set -Ux AICHAT_LIGHT_THEME 0"
fi
