#!/usr/bin/env fish

set -l script_dir (dirname (realpath (status --current-filename)))
set -l dotfiles_dir (realpath "$script_dir/../../..")

set -l update_commands \
    "make -C $dotfiles_dir mise-update" \
    "make -C $dotfiles_dir pnpm-update" \
    "make -C $dotfiles_dir npm-update" \
    "make -C $dotfiles_dir brew-update" \
    "make -C $dotfiles_dir gh-update" \
    "make -C $dotfiles_dir fisher" \
    "make -C $dotfiles_dir uv-update"

function print_header
    set_color --bold
    echo ""
    echo --------------------------------------------------
    echo "   " $argv
    echo --------------------------------------------------
    echo ""
    set_color normal
end

for cmd in $update_commands
    print_header "$cmd"
    fish -c "$cmd"
end
