#!/usr/bin/env fish

set -l update_commands \
    "mise upgrade --yes && mise prune --yes" \
    "pnpm update --global" \
    "brew upgrade" \
    "gh extension upgrade --all" \
    "fisher update"

function print_header
    set_color --bold
    echo ""
    echo --------------------------------------------------
    echo "   " $argv
    echo --------------------------------------------------
    echo ""
    set_color normal
end

for cmd in $update_commands
    print_header "$cmd"
    fish -c "$cmd"
end
