tap "hudochenkov/sshpass"

brew "bash"
brew "bat"
brew "coreutils"
brew "dash-shell"
brew "delta"
brew "direnv"
brew "eza"
brew "fd"
brew "findutils"
brew "fish"
brew "fisher"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "hudochenkov/sshpass/sshpass"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lf"
brew "mas"
brew "mise"
brew "moreutils"
brew "ncdu"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "tealdeer"
brew "trash"
brew "zoxide"

cask_args force: true

cask "docker-desktop", greedy: true
cask "firefox", greedy: true
cask "font-iosevka"
cask "ghostty", greedy: true
cask "gitify", greedy: true
cask "itsycal", greedy: true
cask "kitty", greedy: true
cask "nikitabobko/tap/aerospace", greedy: true
cask "obsidian", greedy: true
cask "restfox", greedy: true
cask "spotify"
cask "swiftbar", greedy: true
