require("packer").startup({
  function(use)
    use({
      { "airblade/vim-rooter", config = function() vim.g.rooter_silent_chdir = 1 end },
      { "anuvyklack/hydra.nvim" },
      { "asheq/close-buffers.vim" },
      { "cormacrelf/dark-notify", config = function() require("dark_notify").run() end },
      { "honza/vim-snippets" },
      { "https://gitlab.com/yorickpeterse/nvim-pqf.git", config = function() require("pqf").setup() end },
      { "iamcco/markdown-preview.nvim", run = function() vim.fn["mkdp#util#install"]() end },
      { "ibhagwan/fzf-lua", config = require("plugin-configs.fzf") },
      { "joosepalviste/nvim-ts-context-commentstring" },
      { "junegunn/vim-easy-align" },
      { "lewis6991/gitsigns.nvim", config = require("plugin-configs.gitsigns") },
      { "lukas-reineke/indent-blankline.nvim", config = require("plugin-configs.indent-blankline") },
      { "mbbill/undotree", config = function() vim.g.undotree_HelpLine = 0 end },
      { "mcauleypenney/tidy.nvim" },
      { "mcchrish/zenbones.nvim", config = require("plugin-configs.zenbones") },
      { "neoclide/coc.nvim", branch = "release", config = require("plugin-configs.coc") },
      { "nvchad/nvim-colorizer.lua", config = require("plugin-configs.colorizer") },
      { "nvim-lualine/lualine.nvim", config = require("plugin-configs.lualine") },
      { "nvim-pack/nvim-spectre", requires = "nvim-lua/plenary.nvim", config = require("plugin-configs.spectre") },
      { "nvim-treesitter/nvim-treesitter", run = ":TSUpdate", config = require("plugin-configs.treesitter") },
      { "puremourning/vimspector", setup = require("plugin-configs.vimspector") },
      { "rmagatti/auto-session", config = function() require("auto-session").setup({ log_level = "error" }) end },
      { "romainl/vim-qf" },
      { "sheerun/vim-polyglot" },
      { "tamago324/lir.nvim", requires = { "nvim-lua/plenary.nvim" }, config = require("plugin-configs.lir") },
      { "tpope/vim-commentary" },
      { "tpope/vim-fugitive" },
      { "tpope/vim-repeat" },
      { "tpope/vim-rhubarb" },
      { "tpope/vim-surround" },
      { "tpope/vim-unimpaired" },
      { "tversteeg/registers.nvim", config = require("plugin-configs.registers") },
      { "wbthomason/packer.nvim" },
      { "wellle/targets.vim" },
      { "windwp/nvim-autopairs", config = require("plugin-configs.nvim-autopairs") },
      { "windwp/nvim-ts-autotag" },
    })
  end,
})
