#!/usr/bin/env zsh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=space_changed action="zsh ~/.config/yabai/yabai-destroy_empty_spaces.zsh"

yabai -m config layout                     bsp
yabai -m config auto_balance               on

yabai -m config top_padding                $WM_SPACING
yabai -m config bottom_padding             $WM_SPACING
yabai -m config left_padding               $WM_SPACING
yabai -m config right_padding              $WM_SPACING
yabai -m config window_gap                 $WM_SPACING

yabai -m config normal_window_opacity      0.85
