#!/usr/bin/env zsh

alias -- -="cd -"
alias cp="cp -riv"
alias find="gfind"
alias grep='grep --color=auto'
alias ls="exa"
alias ll="exa -lagh --git --group-directories-first"
alias mkdir="mkdir -vp"
alias mv="mv -iv"
alias reset="tput reset"
alias clear="reset"

alias ejectall="osascript -e 'tell application \"Finder\" to eject (every disk whose ejectable is true)'"
alias n="cd $HOME/Documents/Notes && $EDITOR -c 'Explore'"
alias sz="source $HOME/.zshrc && clear"
alias up="$HOME/.config/scripts/update"

alias y="yarn"
alias ya="yarn add"
alias yad="yarn add -D"
