#!/usr/bin/env zsh

lfwrapper () {
  tmp="$(mktemp)"
  columns="$(tput cols)"
  size="small"

  if [ $columns -gt 200 ]; then
    size="large"
  elif [ $columns -gt 100 ]; then
    size="medium"
  fi

  lf -command "$size" -last-dir-path="$tmp"

  if [ -f "$tmp" ]; then
    dir="$(cat "$tmp")"
    rm -f "$tmp"
    if [ -d "$dir" ]; then
      if [ "$dir" != "$(pwd)" ]; then
        cd "$dir"
      fi
    fi
  fi
}

ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    BUFFER="fg"
    zle accept-line
  else
    zle push-input
    zle clear-screen
  fi
}
zle -N ctrl-z
bindkey '^Z' ctrl-z

# Allow passing dir/filename to cd
cd() {
  [[ ! -e $argv[-1] ]] || [[ -d $argv[-1] ]] || argv[-1]=${argv[-1]%/*}
  builtin cd "$@"
}

jAndLaunch() {
  if [ -d "$2" ] || [ -f "$2" ]; then
    print -Pn "\e]0;%~: $1\a" && $1 "$2"
  elif [ -z "$2" ]; then
    print -Pn "\e]0;%~: $1\a" && $1
  else
    j "$2" && print -Pn "\e]0;%~: $1\a" && $1
  fi
}

l() {
  jAndLaunch lfwrapper $1
}

v() {
  jAndLaunch $EDITOR $1
}

g() {
  export LG_CONFIG_FILE=~/.config/lazygit/config-shared.yml

  LG_CONFIG_FILE+=,

  if [ $DARK_MODE_ACTIVE = 1 ]; then
    LG_CONFIG_FILE+=~/.config/lazygit/config-dark.yml
  else
    LG_CONFIG_FILE+=~/.config/lazygit/config-light.yml
  fi

  jAndLaunch lazygit "$1"
}
