alias \
  -- -='cd -' \
  dot="cd $DOTDIR" \
  ejectall="osascript -e 'tell application \"Finder\" to eject (every disk whose ejectable is true)'" \
  ga="git add" \
  gap="git add --patch" \
  gcm="git checkout master" \
  gf='git fetch' \
  gl="git pull" \
  gp="git push" \
  gs="git status" \
  ls="ls -lAh" \
  n="$EDITOR $HOME/Documents/notes.md" \
  nci="npm clean-install" \
  ni="npm install" \
  nise="npm install --save-exact" \
  nrb="npm run build" \
  nrd="npm run dev" \
  ns="npm start" \
  nt="npm test" \
  nu="npm uninstall" \
  sm="smerge ./" \
  v="$EDITOR" \
