abbr -a .. "cd .."
abbr -a dotvim "vim ~/.config/nvim/init.vim"
abbr -a lg "lazygit"
abbr -a ls "exa -lah --git-ignore --group-directories-first --git --color-scale"
abbr -a ssh "kitty +kitten ssh"
abbr -a tree "tree -I 'node_modules|cache|next'"
abbr -a v "nvim"
abbr -a vi "nvim"
abbr -a vim "nvim"

abbr -a ga "git add"
abbr -a gaa "git add --all ."
abbr -a gb "git branch"
abbr -a gba "git branch -a"
abbr -a gbd "git branch -D"
abbr -a gca "git commit -a -m"
abbr -a gcm "git checkout master"
abbr -a gco "git checkout"
abbr -a gcob "git checkout -b"
abbr -a gd "git diff -M"
abbr -a gf "git fetch --all --prune"
abbr -a gl "git pull"
abbr -a gp "git push"
abbr -a gpom "git pull origin master"
abbr -a grh "git reset --hard"
abbr -a gs "git status"

abbr -a dm "dark-mode; exec fish"

abbr -a nin "npm install"
abbr -a nrd "npm run dev"
abbr -a nrl "npm run lint"
abbr -a nrt "npm run test"
