abbr -a code "cd ~/code"
abbr -a dot  "cd ~/code/dotfiles"

abbr -a sm   "smerge ./ -n"
abbr -a .    "open ."

abbr -a ls   "exa -lah --git-ignore --group-directories-first --git --color-scale"
abbr -a ssh  "kitty +kitten ssh"
abbr -a v    "nvim"
abbr -a vim  "nvim"

abbr -a ga   "git add"
abbr -a gap  "git add --patch"
abbr -a gaa  "git add --all ."
abbr -a gcm  "git checkout master"
abbr -a gcob "git checkout -b"
abbr -a gd   "git difftool"
abbr -a gf   "git fetch --all --prune"
abbr -a gl   "git pull"
abbr -a gp   "git push"
abbr -a grh  "git reset --hard"
abbr -a gs   "git status"

abbr -a dm   "dark-mode; exec fish"
abbr -a dtl  "lsof -U | grep dtach"

abbr -a nin  "npm install --save-exact"
abbr -a nci  "npm ci"
abbr -a nrd  "npm run dev"
abbr -a nrl  "npm run lint"
abbr -a nrt  "npm run test"
