#!/usr/bin/env zsh

theme=$([[ "$argv" = "light" ]] && echo "$KITTY_THEME_LIGHT" || echo "$KITTY_THEME_DARK")
kitty @ --to unix:/tmp/mykitty set-colors -a -c ~/.config/kitty/themes/$theme.conf
ln -sf ~/.config/kitty/themes/$theme.conf ~/.config/kitty/theme.conf
mkdir -p "$HOME/Library/Application Support/jesseduffield/lazygit"
ln -sf $HOME/.config/lazygit/config-$argv.yml "$HOME/Library/Application Support/jesseduffield/lazygit/config.yml"
